spring:
  profiles:
    active: jpa

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  port: 8081